version: 2
builds:
  - id: turnecho
    main: ./cmd/turnecho
    binary: turnecho
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    ignore:
      - goos: linux
        goarch: arm64
    ldflags:
      - -X github.com/rmscoal/turnecho/internal/version.Version={{.Version}}
archives:
  - formats: [tar.gz]
checksum:
  name_template: checksums.txt
